apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: employee-js-bundle
spec:
  rawFrom:
    url: http://{{ include "frontend.fullname" . }}.{{ .Release.Namespace }}.svc/dist/employee-frontend/index.js
status:
  state: Available
  link: /dist/{{ include "frontend.fullname" . }}/index.js
