apiVersion: v1
kind: Namespace
metadata:
  name: sharing-secret

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharing-secret
rules:
  - verbs:
      - '*'
    resources:
      - 'secrets'
      - 'sharingsecrets'
    apiGroups:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sharing-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sharing-secret
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sharing-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sharing-secret-controller
  name: sharing-secret-controller
  namespace: sharing-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharing-secret-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sharing-secret-controller
    spec:
      containers:
        - image: wansir/sharing-secret:latest
          imagePullPolicy: Always
          name: sharing-secret